[build]
  publish = "."

[[redirects]]
  from = "/research-report"
  to = "/research-report.html"
  status = 200

[[redirects]]
  from = "/journal"
  to = "/journal.html"
  status = 200

[[redirects]]
  from = "/journal/*"
  to = "/journal/:splat.html"
  status = 200
