const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const nav=q('.site-nav'),toggle=q('.mobile-toggle');
if(toggle){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.textContent=open?'Close':'Menu';});}
if('IntersectionObserver' in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});qa('.reveal').forEach(el=>io.observe(el));}else qa('.reveal').forEach(el=>el.classList.add('visible'));
const progress=q('.progress');if(progress){const update=()=>{const d=document.documentElement;const max=d.scrollHeight-d.clientHeight;progress.style.width=(max?d.scrollTop/max*100:0)+'%'};addEventListener('scroll',update,{passive:true});update();}
const orbitCopy=q('[data-orbit-copy]');const orbitText={n1:'A question you have not asked yet.',n2:'An assumption that may not be fixed.',n3:'A perspective outside your usual circle.',n4:'Relevant experience without a vested interest.',n5:'A risk or option you may have overlooked.',n6:'The same question seen from another angle.'};qa('[data-orbit-node]').forEach(b=>b.addEventListener('click',()=>{qa('[data-orbit-node]').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');if(orbitCopy)orbitCopy.textContent=orbitText[b.dataset.orbitNode]||'';}));
const councilData={
 ask:['Ask questions','The other women help surface what may be underneath the decision, not simply react to the version first presented.'],
 challenge:['Challenge assumptions','Useful disagreement matters. A Council can question what is being treated as fixed, inevitable or already decided.'],
 perspective:['Bring perspective','Members bring different professional contexts, experiences and ways of seeing the same problem.'],
 experience:['Share relevant experience','Experience is useful when it illuminates the question rather than becoming a prescription.'],
 stress:['Stress-test the thinking','A plan, decision or interpretation can be tested before it is acted on.'],
 context:['Build context over time','The same six women return each month, so the room develops context that a one-off conversation cannot.']
};
const cpTitle=q('[data-council-title]'),cpBody=q('[data-council-body]');qa('[data-council-seat]').forEach(b=>b.addEventListener('click',()=>{qa('[data-council-seat]').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');const d=councilData[b.dataset.councilSeat];if(d){cpTitle.textContent=d[0];cpBody.textContent=d[1];}}));
const editions={transition:['Transition','For women making a significant change in professional direction.','Changing roles or sectors, returning after time away, dealing with redundancy, changing how you work or leaving something established.'],visibility:['Visibility & Momentum','For women thinking seriously about what comes next.','Greater visibility, responsibility, influence or momentum when the obvious next step is no longer obvious.'],recalibration:['Recalibration','For women reconsidering the shape of their professional life.','What stays, what changes, and whether the version of success you were pursuing still fits.']};
const et=q('[data-edition-title]'),ed=q('[data-edition-dek]'),eb=q('[data-edition-body]');qa('[data-edition]').forEach(b=>b.addEventListener('click',()=>{qa('[data-edition]').forEach(x=>x.setAttribute('aria-selected','false'));b.setAttribute('aria-selected','true');const d=editions[b.dataset.edition];if(d){et.textContent=d[0];ed.textContent=d[1];eb.textContent=d[2];}}));
qa('.theme-item button').forEach(b=>b.addEventListener('click',()=>{const item=b.closest('.theme-item');const open=item.classList.contains('open');qa('.theme-item').forEach(i=>i.classList.remove('open'));if(!open)item.classList.add('open');b.setAttribute('aria-expanded',String(!open));}));
const form=q('[data-application-form]'),status=q('[data-form-status]');if(form){form.addEventListener('submit',async e=>{e.preventDefault();const btn=q('button[type=submit]',form);status.textContent='Submitting…';status.className='form-status';btn.disabled=true;try{const payload=Object.fromEntries(new FormData(form).entries());const r=await fetch('/.netlify/functions/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Submission failed');status.className='form-status success';status.textContent='Thank you. Your application has been submitted.';form.reset();}catch(e){status.className='form-status error';status.textContent='We could not submit your application. Please try again.';}finally{btn.disabled=false;}})}
